### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Hordyna-Dmytro** [Hordyna-Dmytro/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by DmitryHordyna** [comment]
скільки ти будеш ще тянути

**Comment by Hordyna-Dmytro** [comment]
пострараюсь
